services:
  search:
    build: .
    volumes:
      - .:/app
    environment:
      - STFU_MODE=false
      - PYTHONUNBUFFERED=1
      - NUM_THREADS=1
    command: ["SEARCH"]  # "SEARCH" or "DYNAMIC"

  # chrome0:
  #   image: selenium/node-chrome:4.20.0-20240505
  #   shm_size: 2gb
  #   depends_on:
  #     - selenium-hub
  #   environment:
  #     - SE_EVENT_BUS_HOST=selenium-hub
  #     - SE_EVENT_BUS_PUBLISH_PORT=4442
  #     - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    
  # chrome1:
  #   image: selenium/node-chrome:4.20.0-20240505
  #   shm_size: 2gb
  #   depends_on:
  #     - selenium-hub
  #   environment:
  #     - SE_EVENT_BUS_HOST=selenium-hub
  #     - SE_EVENT_BUS_PUBLISH_PORT=4442
  #     - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  
  # chrome2:
  #   image: selenium/node-chrome:4.20.0-20240505
  #   shm_size: 2gb
  #   depends_on:
  #     - selenium-hub
  #   environment:
  #     - SE_EVENT_BUS_HOST=selenium-hub
  #     - SE_EVENT_BUS_PUBLISH_PORT=4442
  #     - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  # selenium-hub:
  #   image: selenium/hub:4.20.0-20240505
  #   container_name: selenium-hub
  #   ports:
  #     - "4442:4442"
  #     - "4443:4443"
  #     - "4444:4444"