# Use an official Python runtime as a parent image
FROM node

# Copy the current directory contents into the container at /app
RUN mkdir /app

# Set the working directory to /app
WORKDIR /app


ENTRYPOINT ["tail", "-f", "/dev/null"]